CREATE TABLE TBL_SUPERHEROE (
    id   INTEGER      NOT NULL AUTO_INCREMENT,
    name VARCHAR(128) NOT NULL,
    PRIMARY KEY (id)
);
INSERT INTO TBL_SUPERHEROE (ID, NAME) VALUES (1, 'Batman');
INSERT INTO TBL_SUPERHEROE (ID, NAME) VALUES (2, 'SuperMan');
INSERT INTO TBL_SUPERHEROE (ID, NAME) VALUES (3, 'HombreAraña');